[package]
name = "reskit-mux"
version = "0.1.0"
authors = ["yunfei.liu <yunfei.liu@alibaba-inc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
route-recognizer = "0.3"
